FROM gcc:13.2

LABEL base-image-name="whanos-c"

ONBUILD SHELL ["/bin/bash", "-c"]
ONBUILD ENV SHELL=/bin/bash

##

WORKDIR /app

ONBUILD COPY Makefile /app

ONBUILD RUN if [ ! -f Makefile ]; then echo "Makefile not found!" && exit 1; fi

ONBUILD COPY /app /app/app

ONBUILD RUN make -j4 \
    && make clean \
    && rm -rf /tmp/* /var/tmp/*

ONBUILD RUN if [ ! -f ./compiled-app ]; then echo "compiled-app not found, it should be place in the root of the repository!" && exit 1; fi
