---
- name: Deploy Jenkins
  hosts: all
  become: true
  vars:
    jenkins_pwd: "{{ lookup('env', 'JENKINS_USER_PASSWORD') }}"
  tasks:
    - name: Create directory for images
      file:
        path: /opt/docker-base-images/
        state: directory
        mode: "0755"
      tags:
        - copy-files

    - name: Copy Docker images to /opt/images
      copy:
        src: ../images/
        dest: /opt/docker-base-images/
        mode: "0755"
      tags:
        - fast-image-copy
        - copy-files

    - name: Create directory for jenkins configuration files
      file:
        path: /opt/jenkins_scripts/
        state: directory
        mode: "0755"
      tags:
        - copy-files

    - name: Copy Jenkins Configuration as Code files to /opt/jenkins_scripts
      copy:
        src: ../jenkins/
        dest: /opt/jenkins_scripts/
        mode: "0755"
      tags:
        - copy-files
        - fast-script-copy

    ##############

    - name: Install Jenkins dependencies # jre and acl
      apt:
        name:
          - openjdk-17-jre
          - acl
        state: present

    ## Install Configuration files ##

    - name: Create directory for images
      file:
        path: /opt/jenkins
        state: directory
        mode: "0755"
      tags:
        - jcasc

    - name: Deploy Jenkins via JCasC
      vars:
        jenkins_install_java: false
        jenkins_jcasc_config_file: "../jenkins/jenkins.yml.j2"
        jenkins_plugins_file: "../jenkins/plugins.yml"
        jenkins_root: "/opt/jenkins"
        jenkins_start_service: true
        jenkins_version: 2.479.2
        jenkins_pimt_args: "--latest false"
        jenkins_web_user: "admin"
        jenkins_web_password: "{{ jenkins_pwd }}"
      import_role:
        name: ableton.jenkins_jcasc
      tags:
        - jcasc

    ## Docker Permissions ##

    - name: Add Jenkins user to the docker group
      user:
        name: jenkins
        groups: docker
        append: true
      tags:
        - docker

  ## Jenkins Scripts Dependencies ##

    - name: Copy Requirements file
      copy:
        src: ../jenkins/python_requirements.txt
        dest: /opt/jenkins_scripts/
        mode: "0755"
      tags:
        - jenkins-scripts

    - name: Install Python3 and Pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
      tags:
        - jenkins-scripts

    - name: Install Python dependencies
      pip:
        requirements: /opt/jenkins_scripts/python_requirements.txt
        break_system_packages: true
      tags:
        - jenkins-scripts
