---

- name: Deploy Docker Registry
  hosts: all
  become: true # sudo
  tasks:
    # https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-20-04
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: true

    ##########

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true
