---
- name: Install Kubernetes and kubectl
  hosts: all
  become: true
  vars:
    gcp_project_id: "{{ lookup('env', 'TF_VAR_gcp_project_id') }}"
    gcp_region: "{{ lookup('env', 'TF_VAR_gcp_region') }}"

  tasks:
    - name: Install Google Cloud SDK Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Download Google Cloud public signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
        keyring: /usr/share/keyrings/cloud.google.gpg

    - name: Add Google Cloud SDK repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
        state: present
        filename: google-cloud-sdk

    - name: Update apt package index
      apt:
        update_cache: true

    - name: Install Google Cloud SDK / Kubectl
      apt:
        name:
          - google-cloud-sdk
          - google-cloud-cli-gke-gcloud-auth-plugin
          - kubectl
        state: present

    - name: Create directory for auth file
      file:
        path: /opt/auth
        state: directory
        mode: '0755'

    - name: Copy Auth File
      copy:
        src: keys/whanos_gke.json
        dest: /opt/auth/whanos_gke.json
        mode: '0644'

    - name: Authenticate to Google Cloud
      command: gcloud auth activate-service-account --key-file /opt/auth/whanos_gke.json
      become: true
      become_user: jenkins

    - name: Set Google Cloud project
      command: gcloud config set project {{ gcp_project_id }}
      become: true
      become_user: jenkins

    - name: Set compute zone
      command: gcloud config set compute/zone {{ gcp_region }}
      become: true
      become_user: jenkins

    - name: Get credentials for GKE cluster
      command: gcloud container clusters get-credentials "whanos-gke-cluster"
      become: true
      become_user: jenkins

    ## Registry GKE secrets ##

    - name: Create directory for kubernetes configuration files
      file:
        path: /opt/k8s/
        state: directory
        mode: "0755"
      tags:
        - copy-files
        - docker

    - name: Copy Kubernetes configuration files to /opt/k8s
      copy:
        src: ../kubernetes/
        dest: /opt/k8s/
        mode: "0755"
      tags:
        - copy-files
        - docker

    - name: Copy terraform output
      copy:
        src: ./setup-google/terraform_outputs.sh
        dest: /opt/terraform_outputs.sh
        mode: '0744'
      tags:
        - docker

    - name: Export terraform outputs
      shell:
        cmd: |
          . /opt/terraform_outputs.sh
          echo "$HEAD_IP" > /opt/auth/head_ip
          echo "$PROJECT_ID" > /opt/auth/project_id
        executable: /bin/bash
      tags:
        - docker

    - name: Set Cluster docker registry secrets
      shell: >
        kubectl create secret docker-registry registry-key \
            --docker-server="https://gcr.io" \
            --docker-username="_json_key" \
            --docker-password="$(cat /opt/auth/whanos_gke.json)" \
            --namespace=kube-system || true
      become: true
      become_user: jenkins
      tags:
        - docker

    ## GCE ##

    - name: Enable gcr.io
      command: gcloud auth configure-docker --quiet
      become: true
      become_user: jenkins
