FROM python:3.12-alpine3.21

LABEL base-image-name="whanos-python"

ONBUILD RUN apk add --no-cache bash

ONBUILD SHELL ["/bin/bash", "-c"]
ONBUILD ENV SHELL=/bin/bash

##

WORKDIR /app

ONBUILD COPY requirements.txt /app

ONBUILD RUN if [ ! -f requirements.txt ]; then echo "requirements.txt not found!" && exit 1; fi

ONBUILD RUN pip install -r requirements.txt --break-system-packages \
    && pip cache purge \
    && rm -rf /root/.cache

ONBUILD COPY /app /app
