FROM node:20.9-alpine

LABEL base-image-name="whanos-javascript"

ONBUILD RUN apk add --no-cache bash

ONBUILD SHELL ["/bin/bash", "-c"]
ONBUILD ENV SHELL=/bin/bash

##

WORKDIR /app

ONBUILD COPY package.json /app

ONBUILD RUN if [ ! -f package.json ]; then echo "package.json not found!" && exit 1; fi

ONBUILD RUN  npm install \
    && npm cache clean --force \
    && rm -rf /tmp/* /var/tmp/*

ONBUILD COPY /app /app
